{{- if .Values.ingress.enable }}
{{- $root := . -}}
{{- $release := .Release -}}
{{- range .Values.ingress.hosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ regexReplaceAll "\\." .host "-" }}
  namespace: {{ $release.Namespace }}
  annotations: {{- toYaml .annotations | nindent 4 }}
spec:
  ingressClassName: {{ $root.Values.ingress.className }}
  rules:
  - host: {{ required "A .host must be entered for all ingress entries" .host }}
    http:
      paths:
      - path: {{ default "/(.*)" .path }}
        pathType: {{ default "Prefix" .pathType }}
        backend:
          service:
            name: {{ $release.Name }}
            port:
              number: {{ default 80 $root.Values.nginx.service.port | int }}
  tls:
  {{ if .tlsSecretName }}
  - hosts:
    - "{{ .host }}"
    secretName: {{ .tlsSecretName }}
  {{ end }}
---
{{- end }}
{{- end }}
