apiVersion: v1
kind: Secret
metadata:
  name: "password-{{ .Release.Name }}"
  namespace: {{ .Values.namespace }}
data:
  # SSH password secret. Can be retrieved using kubectl:
  # kubectl get secret -n <namespace> password-<releasename> -o jsonpath="{.data.ssh-password}" | base64 --decode
  ssh-password: {{ randAlphaNum 30 | b64enc }}
