apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if eq .Values.service.type "NodePort" }}
  externalTrafficPolicy: "Local"
  {{ end }}
  ports:
    - name: http
      port: {{ required "A valid .Values.nginx.service.port must be set!" .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.nginx.service.port }}
      {{ end }}
    - name: ssh
      port: {{ required "A valid .Values.ssh.service.port must be set!" .Values.ssh.service.port }}
      targetPort: ssh
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.ssh.service.port }}
      {{ end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
