# InspIRCd default values
service:
  type: ClusterIP
  ports:
    clients: 6667
    clientsSSL: 6697
    servers: 7000
container:
  ports:
    clients: 6667
    clientsSSL: 6697
    servers: 7000
image:
  repository: inspircd/inspircd-docker
  pullPolicy: IfNotPresent
  tag: 2.0.26
serviceAccount:
  create: true
  name: "inspircd"
  annotations: {}
resources: {}
server:
  motd: "Welcome!
 
This server is running InspIRCd in Kubernetes via Helm.
Deploy your server at https://juppi88.github.io/helm-charts today!"
