apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.conf: '
<files motd="/inspircd/conf/motd">'
  motd: '{{ .Values.server.motd }}'
