apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if eq .Values.service.type "NodePort" }}
  externalTrafficPolicy: "Local"
  {{ end }}
  ports:
    - name: irc-client
      port: {{ required "A valid .Values.service.ports.clients is required" .Values.service.ports.clients }}
      targetPort: irc-client
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.clients }}
      {{ end }}
    - name: irc-client-ssl
      port: {{ required "A valid .Values.service.ports.clientsSSL is required" .Values.service.ports.clientsSSL }}
      targetPort: irc-client-ssl
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.clientsSSL }}
      {{ end }}
    - name: irc-server
      port: {{ required "A valid .Values.service.ports.servers is required" .Values.service.ports.servers }}
      targetPort: irc-server
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.servers }}
      {{ end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
