apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{ if eq .Values.service.type "NodePort" }}
  externalTrafficPolicy: "Local"
  {{ end }}
  ports:
    - name: irc-client
      port: {{ required "A valid .Values.service.ports.client" .Values.service.ports.client }}
      targetPort: irc-client
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.client }}
      {{ end }}
    - name: irc-client-ssl
      port: {{ required "A valid .Values.service.ports.clientSSL" .Values.service.ports.clientSSL }}
      targetPort: irc-client-ssl
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.clientSSL }}
      {{ end }}
    - name: irc-server
      port: {{ required "A valid .Values.service.ports.server" .Values.service.ports.server }}
      targetPort: irc-server
      protocol: TCP
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.ports.server }}
      {{ end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
