apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: webhook
      port: {{ required "A valid .Values.service.port is required" .Values.service.port }}
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
